### ISSUE TITLE
Multi motifs ?

### ISSUE THREAD

**Issue by damda58** [noodom/jeedom_scenarios#1]
Est-il possible de mettre plusieurs motifs ? Par exemple quand on va au boulot et qu'on emmène notre enfant a la nounou ? 
Il faudrait enfant + travail

**Comment by noodom** [comment]
Bonjour,

Pouvez-vous préciser quel est le sujet de la demande ? (quel widget ou menu ou autre ?)
Merci.

**Comment by noodom** [comment]
Il semble que ça concernait la génération d'attestations. Je clos la demande (Merci de refaire si besoin).
